esphome:
  name: smart-shelf
  friendly_name: smart-shelf

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:
    ssid: "Smart-Shelf Fallback Hotspot"
    password: "123456789"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

switch:
  - platform: gpio
    name: "Switch0"
    pin: 26
  - platform: gpio
    name: "Switch1"
    pin: 18
  - platform: gpio
    name: "Switch2"
    pin: 19
  - platform: gpio
    name: "Switch3"
    pin: 23
  - platform: gpio
    name: "Switch4"
    pin: 5
